In [1]:
import numpy as np

# Question 1
**Write a function that takes in a vector and returns a matrix whose columns are the powers of the input vector. (The Vandermonde Matrix)**

In [9]:
def Vandermonde(vector, n):
    # n : number of columns required
    m = len(vector)
    vector = np.array(vector)
    V_matrix = np.zeros((m, n))
    for i in range(0, n):
        V_matrix[:, i] = vector**i
    print(V_matrix)

**Example**

In [10]:
vector = [1, 2, 3, 4]
n = 5
Vandermonde(vector, n)

[[  1.   1.   1.   1.   1.]
 [  1.   2.   4.   8.  16.]
 [  1.   3.   9.  27.  81.]
 [  1.   4.  16.  64. 256.]]


# Question 2
**Write a function to find the moving average in an array over a given window.**

In [16]:
def moving_avg(sequence, window_size):
    num_elts = len(sequence) - window_size + 1      # number of elements in the moving average sequence
    y = []                                          # initializing the moving average sequence
    for i in range(num_elts):
        avg = 0                                     # initializing the average
        for j in range(i, i + window_size):
            avg += sequence[j]                      
        avg = avg / window_size                     # the average element
        y.append(avg)                                 
    print(y)

In [17]:
sequence = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window_size = 3
moving_avg(sequence, window_size)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
